### ISSUE TITLE
incongruent API for subscribeToEvents between iOS and Android

### ISSUE THREAD

**Issue by MrLoh** [SelligentMarketingCloud/MobileSDK-ReactNative#10]
Apart from not having any actual content in the example. The documentation also is wrong in stating that `subscribeToEvents` expects an `errorCallback` as the second and `eventCallback` as the third parameter, when in fact there is no `errorCallback` and the `eventCallback` must be the second argument on iOS. on Android the method is correct.

Was this package ever tested before it was released?

**Comment by MarcBiosca** [comment]
this is solved in latest versions
