### ISSUE TITLE
is there a reason for the Selligent.json

### ISSUE THREAD

**Issue by MrLoh** [SelligentMarketingCloud/MobileSDK-ReactNative#12]
Is there a reason the `selligent.json` file is required, it would be much easier to simply call the `reloadSettings` function to set the correct settings instead of having to setup a json file, especially when having to deal with different configurations depending on staging vs. production environments

**Comment by MarcBiosca** [comment]
This is needed bacause the Native SDKs are loaded before the RN JS code is loaded so if it would be through code it would already be too late for the native SDK, and using the reload function of native SDKs is not an option as these were built for internal purposes and should never be the way to start the SDK as it could cause malfunctions.
