### ISSUE TITLE
missing requiresMainQueueSetup method

### ISSUE THREAD

**Issue by MrLoh** [SelligentMarketingCloud/MobileSDK-ReactNative#13]
This throws a warning

> Module RNSelligent requires main queue setup since it overrides `init` but doesn't implement `requiresMainQueueSetup`. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.

all that is needed to get rid of it is to add the following function on iOS 

```objc
+ (BOOL)requiresMainQueueSetup
 {
     return YES;
 }
```

**Comment by MarcBiosca** [comment]
this is solved in latest versions
