### ISSUE TITLE
Framework does not recognize InfoPlist.strings files

### ISSUE THREAD

**Issue by TheWirv** [SelligentMarketingCloud/MobileSDK-ReactNative#21]
All the strings for `NSLocationAlwaysAndWhenInUseUsageDescription`, `NSLocationWhenInUseUsageDescription`, and `NSLocationAlwaysUsageDescription` are localized in my app, and therefore reside in `InfoPlist.strings` files instead of `Info.plist`.

Now I can't call `requestLocationAuthorisation()` because I get the `SMLib:Error` "NSLocationAlwaysAndWhenInUseUsageDescription must be added in the plist file".

**Comment by MarcBiosca** [comment]
Hi Marcel,
For this kind of problems our ticketing system should be used instead, we don't monitor this normally, it looks like a native SDK check.
What if you add the key in Info.plist and add a default value there? ("If a localized version of a key does not exist, the routines return the value stored in the Info.plist file.")
Another option is to not use the requestLocationAuthorisation() from the SDK/wrapper but request the permission with IOS methods directly.

**Comment by TheWirv** [comment]
Hi Marc,

yes, I added a default value to `Info.plist` for the time being. You're right, this is a native SDK issue and this is not the right place actually for it, sorry.

I didn't know that you guys had a ticketing system. You should add this issue to it, so that the native SDK check will be getting fixed in the future.
