### ISSUE TITLE
Fix documentation to enable images in PNs on ios

### ISSUE THREAD

**Issue by ndbeyer** [SelligentMarketingCloud/MobileSDK-ReactNative#22]
In order to make images show up in selligent PNs, some wrong parts in the documentation, must be fixed.

**IOS - Using the SDK.pdf 6.9.2.3 (swift)**
-  `let setting: SMManagerSetting= SMManagerSetting.setting(url: url, clientID: clientID, privateKey: privateKey)` is wrong, it is `let setting: SMManagerSetting = SMManagerSetting(url: url, clientID: clientID, privateKey: privateKey)`
-  `SMManager.sharedInstance().didReceive(request, withContentHandler: contentHandler as! (UNNotificationContent?) -> Void)` does not work, instead
1) don't provide the contentHandler argument, but call it yourself (this works definitely)
```
let modifiedContent = SMManager.sharedInstance().didReceive(request)
        if let modifiedContent = modifiedContent {
          contentHandler(modifiedContent)
        }
```
2) or dont cast the type (should also work)
```
SMManager.sharedInstance().didReceive(request, withContentHandler: contentHandler)
```

**AppGroup Github: Push notifications 3. Make sure you add your appGroupId to the selligent.json.**
- `group.<your group name>` should be of format of `group.<Main_App_Bundle_Identifier>` e.g. `group.de.todolist.app`, others like e.g. `group.de.todolist.app.selligent.push` don't seem to work
- however, in the `selligent.json`,`group.<your group name>` it must be without `.group`
```
{
  "appGroupId": "de.todolist.app"
}
```

**Comment by MarcBiosca** [comment]
This is now fixed in RN code & documentation and Native IOS documentation
