### ISSUE TITLE
installation instructions are outdated

### ISSUE THREAD

**Issue by MrLoh** [SelligentMarketingCloud/MobileSDK-ReactNative#8]
It is not possible to install this anymore, since there are no instructions for a [RN 0.60 based autolink install](https://reactnative.dev/blog/2019/07/03/version-60) and the old instructions fail on iOS with `Undefined symbols for architecture x86_64: _OBJC_CLASS_$_SMDeviceInfos ...` and on Android with `ERROR: The modules ['android-@selligent-marketing-cloud_selligent-react-native', 'android-selligent-react-native'] point to the same directory in the file system.`

**Comment by MarcBiosca** [comment]
this is solved in latest versions
